name: "Patch font"
on:
  workflow_dispatch: {}
  schedule:
    - cron: "43 16 * * 5" # Run at 16:43 UTC on Friday

permissions:
  contents: write

jobs:
  call_workflow:
    uses: Iosevka-NerdFont/workflows/.github/workflows/patch-font.yml@main
